# Generated by Django 2.2 on 2019-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_post_like_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
