# Generated by Django 2.2 on 2019-07-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20190715_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
