# Generated by Django 2.2 on 2019-07-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20190715_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
