# Generated by Django 2.2.3 on 2019-07-28 11:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_auto_20190728_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='text'),
        ),
    ]
