# Generated by Django 2.2.3 on 2019-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20190626_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='introduce',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
    ]
