# Generated by Django 2.2.3 on 2019-08-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follower_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
